### ISSUE TITLE
Error loading HDFS dataset.

### ISSUE THREAD

**Issue by JinYang88** [LeonYang95/PLELog#10]
Thanks for your great work.

As HDFS labels are initially strings, is this a typo in the following line?  token[1] are strings, which cannot be converted to int.

https://github.com/YangLin-George/PLELog/blob/fd35d79c9bd38b2d087e2241d5a942113013640a/preprocessing/dataloader/HDFSLoader.py#L199

**Comment by nayefroqaya** [comment]
Thanks
